### ISSUE TITLE
有计划适配darkmode么？

### ISSUE THREAD

**Issue by jerryc127** [MiniValine/MiniValine#114]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [ ] I have reviewed the [MiniValine FAQs](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Actual behavior 

- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

## Other Information 

有计划适配darkmode么？

**Comment by MHuiG** [comment]
可搭配Darkmode.js使用
https://github.com/sandoche/Darkmode.js
https://darkmodejs.learn.uno/

**Comment by MHuiG** [comment]
建议启用xCss模式，该模式的样式是全透明的。

**Comment by MHuiG** [comment]
我刚刚尝试部署了一下
https://github.com/MHuiG/hexo-theme-volantis/blob/master-theme/source/css/_third-party/darkmode.styl#L4
好像没有什么需要我去适配的
需要改动的地方大概有
```
.MiniValine .vpage .more
	background: #21232F
img
	filter: brightness(30%)
.MiniValine .vlist .vcard .vcomment-body .text-wrapper .vcomment.expand:before
	background: linear-gradient(180deg, rgba(246,246,246,0), rgba(0,0,0,0.9))
.MiniValine .vlist .vcard .vcomment-body .text-wrapper .vcomment.expand:after
	background: rgba(0,0,0,0.9)
.MiniValine .vlist .vcard .vcomment-body .text-wrapper .vcomment pre
	background: #282c34
	border: 1px solid #282c34
```
详见
https://blog.mhuig.top/about/

**Comment by MHuiG** [comment]
https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-add-dark-mode
