### ISSUE TITLE
Hexo主题Ayer无法适配darkmode

### ISSUE THREAD

**Issue by Shen-Yu** [MiniValine/MiniValine#116]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Other Information 

![image](https://user-images.githubusercontent.com/13065982/83958804-ac7bfb80-a8a8-11ea-8e29-e48b05880405.png)

**Comment by MHuiG** [comment]
https://github.com/Shen-Yu/hexo-theme-ayer/blob/master/layout/_partial/post/minivaline.ejs#L49
删除
```
  #mvcomments-box #mvcomments {
    background-color: #fff;
  }
```
添加
```
  .darkmode .commentTrigger{
	background-color: #403e3e !important;
  }
```

**Comment by MHuiG** [comment]
https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-add-dark-mode

**Comment by MHuiG** [comment]
其他的样式都是透明的，颜色跟随主题

**Comment by MHuiG** [comment]
https://github.com/Shen-Yu/hexo-theme-ayer/pull/61
