### ISSUE TITLE
XCSS模式无法正常提交评论

### ISSUE THREAD

**Issue by suyin-long** [MiniValine/MiniValine#141]
## Issue Checklist 

- [ ] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 
希望可以在Hexo NexT主题上使用XCSS模式

## Actual behavior 

Hexo NexT主题上使用XCSS模式会导致无法提交评论

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: https://github.com/MiniValine/hexo-next-minivaline

## Steps to reproduce the behavior 
1.安装并使用Hexo NexT主题
2.安装[hexo-next-minivaline](https://github.com/MiniValine/hexo-next-minivaline)插件
3.启用XCSS模式
4.提交评论测试

### Node.js and NPM Information

```
v12.18.2
6.14.5
```

### Package dependencies Information

```
hexo-site@0.0.0 E:\Hexo
+-- hexo@4.2.1
+-- hexo-filter-emoji@2.2.1
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@2.2.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-searchdb@1.3.0
+-- hexo-generator-tag@1.0.0
+-- hexo-next-fireworks@1.0.0 (github:next-theme/hexo-next-fireworks#1392a15ad2abebd7f4982f97367524dda3c2fc63)
+-- hexo-next-minivaline@2.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
`-- hexo-symbols-count-time@0.7.1
```

### HTML Configuration

```

```

### MiniValine Configuration

```
mode: DesertsP # DesertsP or xCss
```

## Other Information 
Chrome：83.0.4103.116
System：Windows 10
![1](https://user-images.githubusercontent.com/49554285/87003914-1d3b6e00-c1ef-11ea-8b01-50e8270bc7fa.png)
![2](https://user-images.githubusercontent.com/49554285/87003917-1f053180-c1ef-11ea-885c-d3eb4b82a96e.png)

**Comment by MHuiG** [comment]
我这里是正常的


![image.png](https://imgkr.cn-bj.ufileos.com/cab1f009-e35d-4601-93d5-270dfb4a0761.png)


或许清空一下缓存试试？？

![image.png](https://imgkr.cn-bj.ufileos.com/fda524e8-107e-400c-91d8-fd123b12bed4.png)

**Comment by suyin-long** [comment]
> 我这里是正常的
> 
> ![image.png](https://camo.githubusercontent.com/88acb8c91fb2147f760a1648c6cf4a18d4d7273f/68747470733a2f2f696d676b722e636e2d626a2e7566696c656f732e636f6d2f63616231663030392d653335642d343630312d393364352d3237306466623461303736312e706e67)
> 
> 或许清空一下缓存试试？？
> 
> ![image.png](https://camo.githubusercontent.com/115e605d996d22e2eded604cb4d86624b17205ee/68747470733a2f2f696d676b722e636e2d626a2e7566696c656f732e636f6d2f66646135323465382d313037652d343030632d393164382d6664313233623132626564342e706e67)

我自己简单搭建了个测试网址，您在我这个网址测试下，看看能否正常评论：https://www.suyin-blog.club/

**Comment by MHuiG** [comment]
```
cdn: https://cdn.jsdelivr.net/npm/minivaline@2.8.2/dist/MiniValine.min.js
```

**Comment by suyin-long** [comment]
> ```
> cdn: https://cdn.jsdelivr.net/npm/minivaline@2.8.2/dist/MiniValine.min.js
> ```

经过测试，我将cdn换成你给的这个确实可以正常评论了，但是还有个问题：

**Comment by MHuiG** [comment]
那就刷新一下

**Comment by suyin-long** [comment]
> 那就刷新一下

好吧...
我刚才发现我的评论里不会显示地址，经过测试无论将`NoRecordIP: false`设置为true或false都不会显示地址。
![4](https://user-images.githubusercontent.com/49554285/87027000-1b81a280-c20f-11ea-9c60-0fc7be019c2b.png)
![5](https://user-images.githubusercontent.com/49554285/87027013-1f152980-c20f-11ea-961d-d9bc78b31f8d.png)

还有这个`visitor: true # Article reading statistics.`选项说是文章阅读统计，怎么看不到效果呢？

**Comment by MHuiG** [comment]
文章阅读统计 需要主题开发者适配 

显示地址是Alpha测试功能

如果您想参与 MiniValine Alpha 测试 或者 Beta 测试

自行修改blog\node_modules\hexo-next-minivaline\minivaline.swig文件
![image](https://user-images.githubusercontent.com/38281581/83227178-224fdb00-a1b6-11ea-8e91-4e492c5853f6.png)
![image](https://user-images.githubusercontent.com/38281581/83227260-57f4c400-a1b6-11ea-9d66-380228958a47.png)

```
region : true
```

**Comment by suyin-long** [comment]
> 文章阅读统计 需要主题开发者适配
> 
> 显示地址是Alpha测试功能
> 
> 如果您想参与 MiniValine Alpha 测试 或者 Beta 测试
> 
> 自行修改blog\node_modules\hexo-next-minivaline\minivaline.swig文件
> ![image](https://user-images.githubusercontent.com/38281581/83227178-224fdb00-a1b6-11ea-8e91-4e492c5853f6.png)
> ![image](https://user-images.githubusercontent.com/38281581/83227260-57f4c400-a1b6-11ea-9d66-380228958a47.png)
> 
> ```
> region : true
> ```

ok.
那这个visitor: true # Article reading statistics.选项说是文章阅读统计，怎么看不到效果呢？你们有效果截图吗？我想看一下

**Comment by MHuiG** [comment]
https://github.com/MiniValine/minivaline-counter

```
	<!-- 文章阅读量访问统计 -->
	<!-- id as the query condition -->
	<span id="<Your/Path/Name>" class="leancloud_visitors" data-flag-title="Your Article Title">
		<em class="post-meta-item-text">article reading statistics  </em>
		<i class="leancloud-visitors-count">1000000</i>
	</span>
	<!-- 全站访问统计 -->
	<span id="/" class="leancloud_pv">
		<em class="post-meta-item-text">PV </em>
		<i class="leancloud-visitors-count">1000000</i>
	</span>
```

**Comment by suyin-long** [comment]
> https://github.com/MiniValine/minivaline-counter
> 
> ```
> 	
> 	
> 	<span id="<Your/Path/Name>" class="leancloud_visitors" data-flag-title="Your Article Title">
> 		<em class="post-meta-item-text">article reading statistics  </em>
> 		<i class="leancloud-visitors-count">1000000</i>
> 	</span>
> 	
> 	<span id="/" class="leancloud_pv">
> 		<em class="post-meta-item-text">PV </em>
> 		<i class="leancloud-visitors-count">1000000</i>
> 	</span>
> ```
> 
> > <img alt="" width="48" src="https://avatars2.githubusercontent.com/u/62384464?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[MiniValine/minivaline-counter](https://github.com/MiniValine/minivaline-counter)**minivaline-counter. Contribute to MiniValine/minivaline-counter development by creating an account on GitHub.

好的，我在看看，多谢！

**Comment by MHuiG** [comment]
我不用NexT主题不太会改。。。

hexo-theme-volantis：

https://github.com/theme-volantis/hexo-theme-volantis/blob/master/layout/_meta/counter.ejs

**Comment by suyin-long** [comment]
> 我不用NexT主题不太会改。。。
> 
> hexo-theme-volantis：
> 
> https://github.com/theme-volantis/hexo-theme-volantis/blob/master/layout/_meta/counter.ejs
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/64730988?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[theme-volantis/hexo-theme-volantis](https://github.com/theme-volantis/hexo-theme-volantis)**A Wonderful Theme for Hexo  https://volantis.js.org - theme-volantis/hexo-theme-volantis

你可以参考一下这个：https://valine.js.org/。他这个做的文章阅读统计挺不错的！

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/87032578-6a333a80-c217-11ea-9576-71167e200b19.png)

**Comment by MHuiG** [comment]
需要的话，自己改一下‘’

**Comment by MHuiG** [comment]
https://cuibin1991.github.io/2017/07/31/Hexo%E5%8D%9A%E5%AE%A2next%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0%E6%96%87%E7%AB%A0%E9%98%85%E8%AF%BB%E9%87%8F%E7%BB%9F%E8%AE%A1%E5%8A%9F%E8%83%BD/

**Comment by MHuiG** [comment]
> 他这个做的文章阅读统计挺不错的！

那还是需要主题适配

**Comment by suyin-long** [comment]
> https://cuibin1991.github.io/2017/07/31/Hexo%E5%8D%9A%E5%AE%A2next%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0%E6%96%87%E7%AB%A0%E9%98%85%E8%AF%BB%E9%87%8F%E7%BB%9F%E8%AE%A1%E5%8A%9F%E8%83%BD/

好巧，我想到的也是修改这里达到**文章阅读统计**的目的，但是我刚才试了一下，他这个只会显示阅读数量，而不会显示评论数量。
改图是我修改后的实际结果：
![6](https://user-images.githubusercontent.com/49554285/87034268-27bf2d00-c21a-11ea-97b8-dd445db53045.png)
该图是我期待的结果：
![8](https://user-images.githubusercontent.com/49554285/87034288-3279c200-c21a-11ea-9c4f-b73469b1274c.png)

**Comment by MHuiG** [comment]
这个是NexT主题作者实现的，Valine作者并没有实现

**Comment by suyin-long** [comment]
> 这个是NexT主题作者实现的，Valine作者并没有实现

恩，上边那个图展示的结果是Next作者实现的，下边那个图展示的结果是[Valine](https://valine.js.org/)这个作者实现的

**Comment by MHuiG** [comment]
我刚刚删除了阅读统计这个选项

**Comment by MHuiG** [comment]
话说这里已经有过统计了

![image.png](https://imgkr.cn-bj.ufileos.com/0c031b48-ffae-4d27-8b0e-732484fa2b3d.png)

**Comment by MHuiG** [comment]
感觉放在这里才有意义

![image.png](https://imgkr.cn-bj.ufileos.com/121e4894-b5b5-4abd-8c4e-0e837227c473.png)

**Comment by MHuiG** [comment]
你可以问一下作者是怎么搞定的

https://zhangshuqiao.org/

**Comment by suyin-long** [comment]
> 话说这里已经有过统计了
> 
> ![image.png](https://camo.githubusercontent.com/e819b1800c0e8fb4d142f18d90402ea9c7875233/68747470733a2f2f696d676b722e636e2d626a2e7566696c656f732e636f6d2f30633033316234382d666661652d346432372d386230652d3733323438346661326233642e706e67)
> 
> ![image.png](https://camo.githubusercontent.com/cb1200c6c859cf5941911c7d26a2d22ae0258744/68747470733a2f2f696d676b722e636e2d626a2e7566696c656f732e636f6d2f63363734643636622d323830632d343765632d613862642d6531653561363361653636382e706e67)

这倒是，不过感觉放上好看些

**Comment by suyin-long** [comment]
> 你可以问一下作者米米是怎么搞定的
> 
> https://zhangshuqiao.org/
> 
> > <img alt="" height="14" src="/images/favicon-16x16-next.png"> 米米的博客**[米米的博客](https://zhangshuqiao.org/index.html)**力电声光热，涵尽学海无涯

他这个用的是[valine](https://valine.js.org)这个评论系统，这个Next自带，并且这个评论系统只要配置了，就会显示阅读数量和评论数量

**Comment by suyin-long** [comment]
你可以看我另一个网站：https://suyin-blog.club/
这个网址我用的就是[valine](https://valine.js.org/)这个评论系统，我设置的点击进入文章页面显示阅读数量和评论数，在主页中只显示阅读数量，不显示评论数，如图：
![1](https://user-images.githubusercontent.com/49554285/87039756-3ad5fb00-c222-11ea-8d9a-c27f16e25c8f.png)

**Comment by suyin-long** [comment]
可是关键不是你的这个minivaline功能多，所以尝试一下你这个。

**Comment by suyin-long** [comment]
**提一个小建议：**
评论字体在深色模式下的颜色能不能调亮一点，这样会看的更清楚，如图所示：
![1](https://user-images.githubusercontent.com/49554285/87092841-c2495b80-c26e-11ea-9d70-6c5c7d2ca393.png)
![2](https://user-images.githubusercontent.com/49554285/87092846-c5444c00-c26e-11ea-8d34-de1278cd2041.png)

**Comment by MHuiG** [comment]
样式自己修改css覆盖，我不可能去兼容所有主题
