### ISSUE TITLE
2.8.3版本的一些问题

### ISSUE THREAD

**Issue by suyin-long** [MiniValine/MiniValine#145]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 
xCss样式在深色主题下正常显示

## Actual behavior 

相比于2.8.2版本，2.8.3版本优化了评论字体显示，但是评论用户的头像和评论中的表情显示变得暗了许多。

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 安装MiniValine并使用xCss样式
2. 网站设置为深色模式
3. 使用2.8.3cdn：https://cdn.jsdelivr.net/npm/minivaline@2.8.3/dist/MiniValine.min.js
4. 查看评论显示样式

### Node.js and NPM Information

```
v12.18.2
6.14.5
```

### Package dependencies Information

```
hexo-site@0.0.0 E:\Hexo
+-- bindings@1.5.0
+-- hexo@4.2.1
+-- hexo-enhancer@1.0.7
+-- hexo-filter-emoji@2.2.1
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@2.2.0
+-- hexo-generator-indexed@1.2.0
+-- hexo-generator-searchdb@1.3.0
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-live2d@3.1.1
+-- hexo-next-fireworks@1.0.0 (github:next-theme/hexo-next-fireworks#cf8b3783d2cd681ad6f901934a2beff38e9b7183)
+-- hexo-next-minivaline@2.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-submit-urls-to-search-engine@1.0.1
+-- hexo-symbols-count-time@0.7.1
+-- live2d-widget-model-hijiki@1.0.5
`-- nan@2.14.1
```

### HTML Configuration

```
```

### MiniValine Configuration

```yml
cdn: https://cdn.jsdelivr.net/npm/minivaline@2.8.3/dist/MiniValine.min.js
```

## Other Information 
经过测试，使用`cdn：https://cdn.jsdelivr.net/gh/MiniValine/MiniValine@2.8.3/dist/MiniValine.min.js`结果也是一样
![12](https://user-images.githubusercontent.com/49554285/87220402-ebb0d700-c395-11ea-8908-b60281a2b3d5.png)

**Comment by MHuiG** [comment]
https://github.com/MiniValine/MiniValine/blob/0085a834daafe61c78b6b08b0e7be5a8de761349/src/style/xCss.scss#L764-L766

**Comment by suyin-long** [comment]
我在我fork上的项目上修改，然后再用我的cdn也没用啊。。。
