### ISSUE TITLE
希望为评论增加一个power-mode特效

### ISSUE THREAD

**Issue by suyin-long** [MiniValine/MiniValine#147]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 
在评论的时候可以有power-mode特效 ，演示网站：[点击进入](http://0xabcdef.com/activate-power-mode/)

## Actual behavior 

评论的时候没有power-mode特效

- Links to demo site with this feature:  http://0xabcdef.com/activate-power-mode/
- Links to repository or source code of the blog:  https://github.com/disjukr/activate-power-mode

## Steps to reproduce the behavior 
1. 使用MiniValine评论
2. 写评论

## Other Information 
效果展示视频连接：https://www.bilibili.com/video/BV1Jf4y1R7ys/

**Comment by MHuiG** [comment]
主题里应该有这个特效的吧@sli1989

**Comment by stevenjoezhang** [comment]
主题有插件可以实现这个特效。不过 @suyin-long 已经因为经常提无理要求被我拉黑了( https://github.com/next-theme/hexo-theme-next/issues/49#issuecomment-656223797 )，所以我不太想回答这个问题。抱歉。

**Comment by MHuiG** [comment]
感谢stevenjoezhang ！
