### ISSUE TITLE
Android browser couldn't check comment and comment history(also in Valine)

### ISSUE THREAD

**Issue by Neteraxe** [MiniValine/MiniValine#153]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 
produce comments and comments history

## Actual behavior 
none.
- Links to demo site with this issue:  https://minivaline.github.io/ or valine.js.org
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. browser based on android, no X5 kernel(chrome, Kiwi, 360, X browser, Opera, Via)
2. open link https://minivaline.github.io/ or valine.js.org
3. nothing happen

### Node.js and NPM Information

```
none
```

### Package dependencies Information

```
none
```

### HTML Configuration

```
same as https://minivaline.github.io/ and valine.js.org
```

### MiniValine Configuration

```
same as https://minivaline.github.io/ and valine.js.org
```

## Other Information 
none

**Comment by Neteraxe** [comment]
@monkeywithacupcake @DesertsP @MHuiG @DesertsPan @suyin-long @monkeywithacupcake 
for email notification

**Comment by Neteraxe** [comment]
According to my more observation, it maybe seems like the problem in WebView implementation of my phone, but it still a problem, so is there anyone has a same issue?

**Comment by MHuiG** [comment]
We recommend that you update your browser or operating system. If there is a problem, we are sorry to tell you, because we do not have the environment to reproduce the problem or solve the problem, you will need to use another comment system such as https://github.com/gitalk

**Comment by Neteraxe** [comment]
Android browser, no X5 kernel(such as chrome, Kiwi, 360, X browser, Opera, Via), it won't happen any comment and history.
But my phone has been root and remove more extra application, I'm not sure it's something common or not.

**Comment by MHuiG** [comment]
我这边
Android 5.0.2
360浏览器 9.0.0.152
测试是正常的。

**Comment by MHuiG** [comment]
Opera12.50.0.3也是正常的

**Comment by MHuiG** [comment]
建议您更新您的浏览器或操作系统。如果还有问题，我很抱歉地告诉您，因为我们没有环境来重现问题或解决问题，您需要使用其他评论系统。例如https://github.com/gitalk

**Comment by Neteraxe** [comment]
用其他手机测试也是正常的，可能是我的小米手机缺少正确的webview实现，具体原因实在没有能力得出结论
那问题结束了，只是这也反映了valine系统有一些残缺webview无法实现的功能
android O控制比较严格，也可能是原因

具体情况就是这样了

好像只发到作者邮箱
