### ISSUE TITLE
无法正确获取qq头像

### ISSUE THREAD

**Issue by suyin-long** [MiniValine/MiniValine#180]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 
可以正常显示qq头像

## Actual behavior 

无法正常显示qq头像

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 安装next
2. 安装hexo-next-minivaline
3. 查看评论头像

### Node.js and NPM Information

```
v12.18.3
6.14.6
```

### Package dependencies Information

```
hexo-site@0.0.0 E:\Hexo
+-- hexo@5.1.1
+-- hexo-enhancer@1.0.7
+-- hexo-filter-emoji@2.2.1
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-searchdb@1.3.2
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-live2d@3.1.1
+-- hexo-next-fireworks@1.0.1 (github:next-theme/hexo-next-fireworks#dc3c2eb7c1bbcba7321cf373fb6208df3a75f1d2)
+-- hexo-next-minivaline@2.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.2.0
+-- hexo-renderer-stylus@2.0.0
+-- hexo-server@2.0.0
+-- hexo-submit-urls-to-search-engine@2.0.0
+-- hexo-symbols-count-time@0.7.1
+-- hexo-theme-next@8.0.0
`-- live2d-widget-model-hijiki@1.0.5
```

### HTML Configuration

```

```

### MiniValine Configuration

```
enableQQ: true # Enable QQ avatar API.
```

## Other Information 
以前是可以正常显示qq头像的，如图：
![old](https://user-images.githubusercontent.com/49554285/92251172-04a1b880-eeff-11ea-8985-8eeeeee42a33.png)
现在不会加载qq头像了，如图：
![new](https://user-images.githubusercontent.com/49554285/92251236-1aaf7900-eeff-11ea-95f7-5a22b9b33d69.png)

**Comment by suyin-long** [comment]
已解决，将cdn换成`cdn: https://cdn.jsdelivr.net/gh/MiniValine/MiniValine@3.1.5/dist/MiniValine.min.js`即可！

**Comment by MHuiG** [comment]
https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-improve-the-security-of-minivaline

因安全原因，4.0移除QQ 头像 api
