### ISSUE TITLE
希望 minivaline-counter 增加统计 UV 的功能

### ISSUE THREAD

**Issue by wu-kan** [MiniValine/MiniValine#185]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 

希望站点计数插件可以增加一个统计用户访问量（UV）的功能，这样我就可以完全替换掉之前用的页面计数器不蒜子了…

那个仓库好像没办法发 issue 就先发在这了

## Actual behavior 

- Links to demo site with this feature: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

**Comment by MHuiG** [comment]
https://github.com/volantis-x/hexo-theme-volantis/blob/02cafaab938741549a5fe14cbe4eed633c65cc85/layout/_partial/scripts/counter.ejs#L1-L207

**Comment by MHuiG** [comment]
https://github.com/volantis-x/hexo-theme-volantis/blob/02cafaab938741549a5fe14cbe4eed633c65cc85/layout/_partial/scripts/counter.ejs#L1-L207
