### ISSUE TITLE
Cloudflare Workers 使用方式

### ISSUE THREAD

**Issue by fiammanda** [MiniValine/MiniValine#224]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 
FAQ 中如下内容不太理解，https://minivaline.github.io/ 演示地址中 ID 和 KEY 也直接前端写明了，是否有具体代码？

> We intercept user requests at the edge of the network and judge the validity of the requests. Edge computing is used to dynamically change the request header and replace it with the real API key to forward the request to the back-end database to hide the API key during data interaction.

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### HTML Configuration

```

```

### MiniValine Configuration

```

```

**Comment by MHuiG** [comment]
https://github.com/MiniValine/CF-LC

**Comment by MHuiG** [comment]
就丢一个问题然后人就没影了？？？？

**Comment by MHuiG** [comment]
没有进展，正在关闭
