### ISSUE TITLE
评论框表情包选项无法加载

### ISSUE THREAD

**Issue by lei2rock** [MiniValine/MiniValine#249]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://minivaline.js.org/docs/en/#/FAQ), which does not help me.
- [x] I have searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 

加载表情包

## Actual behavior 

配置信息参见 #248 

表情包无法加载的问题，不知道是什么原因，控制台没见到其他报错
![image](https://user-images.githubusercontent.com/19180725/100538234-71f88780-3269-11eb-9b66-b3bb4e7e4bef.png)

**Comment by MHuiG** [comment]
缓存数据存储在localStorage里了，清空缓存看看

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/100538456-ed0e6d80-326a-11eb-8e5b-fefd808f8d00.png)

**Comment by lei2rock** [comment]
还是没有显示
![image](https://user-images.githubusercontent.com/19180725/100538605-b4bb5f00-326b-11eb-9dbc-4f3d1674d8b0.png)

**Comment by lei2rock** [comment]
补充一个问题： 怎么关闭评论弹幕？

我设置了 `barrage: 0` ，似乎没有用

**Comment by MHuiG** [comment]
每一次更改配置都需要清空localStorage

**Comment by MHuiG** [comment]
等一下，是`barrager:: 0`

**Comment by lei2rock** [comment]
> 等一下，是`barrager: 0` 漏了个r

![image](https://user-images.githubusercontent.com/19180725/100539086-ca7e5380-326e-11eb-8146-10705b23393b.png)

不过问题依然存在，表情包和barrager都一样～（清空localStorage是这样吧
![image](https://user-images.githubusercontent.com/19180725/100539141-57291180-326f-11eb-9e25-0acc261a650d.png)

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/100539168-7f187500-326f-11eb-9d25-825a837cad5c.png)

**Comment by lei2rock** [comment]
我知道，所以改成了barrager: 0，不过问题还是有都，依然关不掉弹幕。那个截图只是提醒一下下面有typo

**Comment by MHuiG** [comment]
`barrager: false`

**Comment by lei2rock** [comment]
> `barrager: false`

似乎还是不行呀～

**Comment by MHuiG** [comment]
这个if返回false就关掉了
https://github.com/MiniValine/MiniValine/blob/bc3908f5201b8a3ae7c6e9c21d82b350b535e9b3/src/MiniValine.js#L55-L58

**Comment by lei2rock** [comment]
但是我这里测试都是关不掉的，和表情包无法加载问题一样，并不因为清除localStorage而解决。（safari 和 Edge无痕模式也尝试过都不行，hexo 使用的命令是 hexo clean && hexo s

**Comment by MHuiG** [comment]
你的localStorage里现在都有什么

**Comment by lei2rock** [comment]
> 你的localStorage里现在都有什么

清除前：
![image](https://user-images.githubusercontent.com/19180725/100539758-8d689000-3273-11eb-9717-16c321e7d98f.png)

清除后：
![image](https://user-images.githubusercontent.com/19180725/100539774-9c4f4280-3273-11eb-9d11-a93c759b6d14.png)

**Comment by MHuiG** [comment]
[index.zip](https://github.com/MiniValine/MiniValine/files/5612024/index.zip)

直接打开这个HTML看看

**Comment by lei2rock** [comment]
> [index.zip](https://github.com/MiniValine/MiniValine/files/5612024/index.zip)
> 
> 直接打开这个HTML看看

本地直接打开的话一切正常，评论可以加载、表情包可以显示、没有弹幕

**Comment by MHuiG** [comment]
那个next插件有点问题

**Comment by lei2rock** [comment]
> 那个next插件有点问题

OK，那我就坐等修复啦～thx

**Comment by ZanderZhao** [comment]
我想起来了，判空和判false效果一样了


 
---原始邮件---
发件人: "H"<notifications@github.com&gt;
发送时间: 2020年11月29日 18:59:33
收件人: "MiniValine/MiniValine"<MiniValine@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [MiniValine/MiniValine] 评论框表情包选项无法加载 (#249)




 
那个next插件有点问题

**Comment by lei2rock** [comment]
> 我想起来了，判空和判false效果一样了

其实设置 `visitor: false` 之后也是没有效果的，依然会记录浏览次数

**Comment by ZanderZhao** [comment]
嗯，插件写错了😂


 
---原始邮件---
发件人: "Donglei Zhang"<notifications@github.com&gt;
发送时间: 2020年11月29日 19:08:33
收件人: "MiniValine/MiniValine"<MiniValine@noreply.github.com&gt;;
抄送: "ZanderZhao"<1310982393@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [MiniValine/MiniValine] 评论框表情包选项无法加载 (#249)




  
我想起来了，判空和判false效果一样了
  
其实设置 visitor: false 之后也是没有效果的，依然会记录浏览次数

**Comment by lei2rock** [comment]
在使用 NexT 插件 `hexo-next-minivaline v5.3.0` 和 `MiniValine v5.0.0-alpha.5`，并且后端程序更新 docker 镜像之后，上述问题（#248、#249）都已经得到解决。撒花🎉 

后续测试如果有问题会进一步反馈，没什么问题我就准备部署MiniValine到我博客啦，感谢！

**Comment by ZanderZhao** [comment]
结论，请使用最新版的`minivaline@>=5.0.0-alpha.5` 和`hexo-next-minivaline@>=5.3.0`
原因，插件传参数错误，且硬避免不合理，在`5.3.0`及其以后改为函数，而不是一个一个写选项
注意，之前的hexo-next-minivaline的~~`appid`和`appkey`~~应该改为`appId`和`appKey`,区分大小写，hexo-next-minivaline`5.3.0`的中文文档有些问题，从`5.3.0`不再兼容小写的`appid`和`appkey`了

**Comment by ZanderZhao** [comment]
> 这个if返回false就关掉了
> https://github.com/MiniValine/MiniValine/blob/bc3908f5201b8a3ae7c6e9c21d82b350b535e9b3/src/MiniValine.js#L55-L58

这个文档需要改吗，barrager可选项的值

**Comment by MHuiG** [comment]
不用改了吧
