### ISSUE TITLE
测试 MiniValine + Waline  + CloudBase 不能获取评论

### ISSUE THREAD

**Issue by eallion** [MiniValine/MiniValine#250]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://minivaline.js.org/docs/en/#/FAQ), which does not help me.
- [x] I have searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 
Null

## Actual behavior 

在测试：`MiniValine` + `Waline` + `CloudBase` 这样的架构，无论是 local 测试还是线上环境都无法获取评论。（可以提交）

## Steps to reproduce the behavior 
1. Hugo latest
2. 评论前端 MiniValine latest
3. 后端 Waline latest
4. 数据库 Waline with CloudBace latest

### Node.js and NPM Information

```
lts
```

### Package dependencies Information

```
without npm
```

### HTML Configuration

```
  {{- if .Site.Params.MiniValine.enable -}}
  <div class="pagination__title">
       <span class="pagination__title-h"><span class="vcount"></span>精彩评论</span>
       <hr />
  </div>
  <div class="mvcomment"></div>
  <script>
  function load_minivaline() {
      setTimeout(function() {
          var HEAD = document.getElementsByTagName('head')[0] || document.documentElement;
          var src = 'https://cdn.jsdelivr.net/npm/minivaline@latest/dist/MiniValine.min.js'
          var script = document.createElement('script')
          script.setAttribute('type','text/javascript')
          script.onload = function() {
             pjax_minivaline()
          }
          script.setAttribute('src', src)
          HEAD.appendChild(script)
      }, 1);
  };
  function pjax_minivaline() {
      if(!document.querySelectorAll(".mvcomment")[0])return;
      new MiniValine({
          el: '.mvcomment',
          backend: 'waline',
          serverURLs: 'My correct Waline backend Server URL',  # <--- it's a real url in my config
          placeholder: '说点什么吧……',
          visitor: true,
          closeFlag: true,
          mode: 'xCss',
          barrager: 0
      });
  }
  load_minivaline();
  document.addEventListener('pjax:complete', function () {
      pjax_minivaline();
  });
  </script>
  {{- end }}
```

### MiniValine Configuration

```
          el: '.mvcomment',
          backend: 'waline',
          serverURLs: 'My correct Waline backend Server URL',  # <--- it's a real url in my config
          placeholder: '说点什么吧……',
          visitor: true,
          closeFlag: true,
          mode: 'xCss',
          barrager: 0
```

**Comment by MHuiG** [comment]
发一下报错信息

**Comment by lei2rock** [comment]
我这边今天上午使用 Hexo NexT + MiniValine + Waline + Tencent CloudBase 是可以正常评论和加载评论的，当然不知道你说的获取评论是获取之前在 CloudBase 上提交的评论还是 Valine 迁移过去的评论。

我觉得可能这个问题在 Waline 仓库提出比较合适，毕竟部署在 CloudBase 是 Waline 的新特性。

**Comment by eallion** [comment]
![image](https://user-images.githubusercontent.com/1698841/100726857-70ad9300-3400-11eb-9ecb-3063826efbfe.png)

可能是不能正确设置 pathname ，试了几个值都不行。

**Comment by eallion** [comment]
> 我这边今天上午使用 Hexo NexT + MiniValine + Waline + Tencent CloudBase 是可以正常评论和加载评论的，当然不知道你说的获取评论是获取之前在 CloudBase 上提交的评论还是 Valine 迁移过去的评论。
> 
> 我觉得可能这个问题在 Waline 仓库提出比较合适，毕竟部署在 CloudBase 是 Waline 的新特性。

前端用 Waline 没有问题。

**Comment by MHuiG** [comment]
window.location.pathname是从哪里来的？

https://github.com/MiniValine/MiniValine/search?q=window.location.pathname&type=

**Comment by eallion** [comment]
一个很奇葩的设定，其他的值必须加引号，`pathname` 不能加引号。
