### ISSUE TITLE
无法正常加载hexo-next-minivaline

### ISSUE THREAD

**Issue by suyin-long** [MiniValine/MiniValine#277]
Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、博客链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/MiniValine/MiniValine/releases/latest) version of MiniValine.
- [x] I have reviewed the [MiniValine FAQs](https://minivaline.js.org/docs/en/#/FAQ), which does not help me.
- [x] I have searched for current [issues](https://github.com/MiniValine/MiniValine/issues), which does not help me.

***

## Expected behavior 
评论正常加载

## Actual behavior 

无论我是用那个版本的hexo-next-minivaline，都无法正常加载评论
- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 安装hexo-next-minivaline
2. 配置hexo-next-minivaline
3. 检查评论显示效果

### Node.js and NPM Information

```
v14.15.4
6.14.10

```

### Package dependencies Information

```
+-- hexo@5.3.0
+-- hexo-enhancer@1.0.10
+-- hexo-filter-emoji@2.2.1
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-searchdb@1.3.3
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-live2d@3.1.1
+-- hexo-next-minivaline@2.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.3.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- hexo-submit-urls-to-search-engine@2.0.0
+-- hexo-symbols-count-time@0.7.1
+-- hexo-theme-landscape@0.0.3
+-- hexo-theme-next@8.2.1
`-- live2d-widget-model-hijiki@1.0.5

```

### HTML Configuration

```

```

### MiniValine Configuration

```

```

## Other Information 
**图示：**
![QQ截图20210205005130](https://user-images.githubusercontent.com/49554285/106927502-34264c80-674d-11eb-8b28-f47f42ae9cbe.png)

**Comment by MHuiG** [comment]
请先升级到v4
https://github.com/MiniValine/hexo-next-minivaline

**Comment by MHuiG** [comment]
需要先升级到 hexo-next-minivaline@5.5.0

这里开源了一个测试demo

https://github.com/MiniValine/test-next

https://minivaline.js.org/test-next/

**Comment by suyin-long** [comment]
> 需要先升级到 hexo-next-minivaline@5.5.0 之前的所有版本都不可用
> 
> 这里开源了一个测试demo
> 
> https://github.com/MiniValine/test-next
> 
> https://minivaline.js.org/test-next/
> 
> > <img alt="" width="48" src="https://avatars.githubusercontent.com/u/62384464?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[MiniValine/test-next](https://github.com/MiniValine/test-next)**test-next. Contribute to MiniValine/test-next development by creating an account on GitHub.
> 
> > <img alt="" height="14" src="/test-next/images/favicon-16x16-next.png"> Hexo**[Hexo](http://yoursite.com/index.html)**

我晚上测试了下，升级到5.5后管用了，参看你们的教程配置了一些参数基本都生效了，只是如图的这些参数不生效，怎么回事？
![QQ截图20210205234329](https://user-images.githubusercontent.com/49554285/107055424-40251380-680c-11eb-9cef-dbec1665a6b8.png)

**Comment by MHuiG** [comment]
https://minivaline.js.org/docs/cn/#/Options?id=xcss-style-mode-options

**Comment by suyin-long** [comment]
> https://minivaline.js.org/docs/cn/#/Options?id=xcss-style-mode-options
> 
> > **[MiniValine](https://minivaline.js.org/docs/cn/#/Options?id=xcss-style-mode-options)**MiniValine

经测试，无论是**本地访客标识**还是**云端访客标识**设置后都不生效
测试版本：hexo-next 8.2.1

**Comment by MHuiG** [comment]
回去把文档抄十遍

**Comment by MHuiG** [comment]
或者可以尝试阅读源码

https://github.com/MiniValine/MiniValine/blob/1d16944f050ba058f6e214eee8b391b7c63f34f1/src/body/vcard.js#L117-L147
